Improvements for better local experience
dpaulson45/HealthChecker pull request #478
Opened 2021-01-22 16:23 UTC by lusassl-msft

This PR contains a fix for issue #474 .
`Test-RequiresServerFqdn` was totally rewritten to detect if the script is executed against the local system. Furthermore this function can detect whether the `Fqdn ` or `NetBIOS name` was passed via `-server` parameter. We do a fallback to the other value when we're not able to connect using the initial (`Fqdn` or `NetBIOS name`) value.

2021-01-26 14:35 UTC, dpaulson45 commented
@lusassl-msft please rebase into 1 commit.

2021-01-26 14:42 UTC, dpaulson45 commented on src/Helpers/Test-RequiresServerFqdn.ps1
> +            $connectionMethod = "Fqdn"
What is the reason for having `$connectionMethod` variable? Doesn't look like we use it for other than setting within this function.

2021-01-26 14:52 UTC, dpaulson45 commented on src/Helpers/Test-RequiresServerFqdn.ps1
> +        {
This seems like a bit of additional logic that might not be needed. Could probably get by with the following:

```
$tempServerName = ($Script:Server).Split(".")

if ($tempServerName[0] -eq $env:COMPUTERNAME) {
    Write-VerboseOutput("Executed against the local machine. No need to pass '-ComputerName' parameter.")
    return
} else {
    $Script:ServerFQDN = (Get-ExchangeServer $Script:Server).FQDN ###maybe should put this in a try catch block itself for if what is passed isn't a valid server not sure if we handle that somewhere else.
}

         try
            {
                Invoke-Command -ComputerName $Script:Server -ScriptBlock {Get-Date | Out-Null} -ErrorAction Stop
                Write-VerboseOutput("Connected successfully using: {0}." -f $connectionMethod)
            }
            catch
            {
                Invoke-CatchActions
                if($tempServerName.Count -gt 1)
                {
                    $Script:Server = $tempServerName[0]
                }
                else
                {
                    $Script:Server = $Script:ServerFQDN
                }
###NEED to try again to see if we can connect, if we can't we need to bail out. Place the invoke-command in it's own function and call to it from each location. 
            }
```

2021-01-26 14:53 UTC, dpaulson45 requested changes
Please see comments for the review of what needs to be changed.

2021-01-27 16:38 UTC, dpaulson45 commented
@lusassl-msft please rebase into a single commit

2021-01-27 17:31 UTC, lusassl-msft reviewed
Rebased as discussed.

2021-01-27 17:33 UTC, dpaulson45 requested changes
Can leave as a second commit.

2021-01-27 17:33 UTC, dpaulson45 commented on src/Helpers/Test-RequiresServerFqdn.ps1
> +            Write-VerboseOutput("Failed to successfully run 'Test-RequiresServerFqdn'")
Let's add an `exit` here and right before we do that, provide with a `Write-Red` that we fail to run `Invoke-Command` against `'$script:Server' and that they should try to run the script locally on that server for results.

2021-01-27 17:42 UTC, lusassl-msft commented on src/Helpers/Test-RequiresServerFqdn.ps1
> +            Write-VerboseOutput("Failed to successfully run 'Test-RequiresServerFqdn'")
Implemented via commit 7774366552d93d70f901545c7df19a3046a45040

2021-01-27 17:50 UTC, dpaulson45 approved these changes

2021-01-27 17:50 UTC, merged