Initial Wiki commit
dpaulson45/HealthChecker pull request #483
Opened 2021-02-01 08:46 UTC by lusassl-msft

PR for the initial wiki content.

2021-02-02 17:46 UTC, dpaulson45 requested changes
See the comments for changes to be requested

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/ExchangeInformation/GeneralServerInformation.md
> +
Add `DAG Name` and `AD Site`

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/ExchangeInformation/MAPIFrontEndAppPoolGCModeCheck.md
> +
Should probably add a section of how to change this as well. Show the default location/app cmdlet to find the config file.

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/FrequentConfigurationIssues/CTSProcessorAffinityPercentageCheck.md
> +This can cause an impact to the server's search performance. This should only be used a temporary fix if no other options are available vs a long term solution.
maybe should provide better wording.

`This should never be used as a long term solution.`

This provides a little more of a strict wording vs a soft.

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/FrequentConfigurationIssues/TCPIPSettingsCheck.md
> +
Maybe provide an example.

`Client -> Firewall (1 hour) -> NLB (40 minutes) -> Exchange Servers (20 Minutes)`

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/NICSettings/GeneralNICInformation.md
> +We show a warning if the NIC driver is older than 1 year
This doesn't show up correctly in mark down. Maybe do the following:


- Driver Date - We show a warning if the NIC diver is older than 1 year.

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/NICSettings/GeneralNICInformation.md
> +- RSS Status
RSS Enabled vs Status. This way it is what we see in the Health Checker itself.

Also add

Max Processors
Max Processor Number
Number of Receive Queues

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/NICSettings/GeneralNICInformation.md
> +**Description:**
Should add how we collect this information. Provide the commands.

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/NICSettings/GeneralNICInformation.md
> +- IPv6 Address
Include (Address, Subnet, Gateway) as well for IPv6

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/NICSettings/GeneralNICInformation.md
> +- Packets Received Discarded
Add what we are checking for here. Why is it Green, Yellow, Red. What does it mean etc.

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/NICSettings/PackageLossCheck.md
> +Package Loss Check
Maybe add this page to the General NIC Information page OR better yet link the two.

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/NICSettings/GeneralNICInformation.md
> +- Packets Received Discarded
Just saw the other page. Might be best to add a link to the other page.

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/NICSettings/PackageLossCheck.md
> +======
Change the name from "Package Loss Check" to "Packets Loss Check"

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/NICSettings/RSSEnabledCheck.md
> +RSS Enabled Check
Either just add this content to General NIC Information, since it is small. Or do what we are doing for Packets Loss Check with a link.

Also provide how we are determining if it is enabled or not.

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/NICSettings/SleepyNICCheck.md
> +======
Provide information on how we are checking for this setting and where from.

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/NICSettings/SleepyNICCheck.md
> +======
Also provide why if we don't find anything in the registry we just assume it is enabled.

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/OSInformation/GeneralOSInformation.md
> +- Power Plan
Missing .NET version

2021-02-02 17:46 UTC, dpaulson45 commented on docs/Checks/OSInformation/GeneralOSInformation.md
> +- Power Plan
Page File
Server Pending Reboot
Visual C++

2021-02-03 18:08 UTC, lusassl-msft commented on docs/Checks/FrequentConfigurationIssues/CTSProcessorAffinityPercentageCheck.md
> +This can cause an impact to the server's search performance. This should only be used a temporary fix if no other options are available vs a long term solution.
Agree. Will change it to the above wording.

2021-02-03 18:12 UTC, lusassl-msft commented on docs/Checks/FrequentConfigurationIssues/TCPIPSettingsCheck.md
> +
Good point. Going to add this example.

2021-02-03 18:25 UTC, lusassl-msft commented on docs/Checks/OSInformation/GeneralOSInformation.md
> +- Power Plan
Will add them to the information page. Don't describe how we perform these checks because we have separate descriptions for these checks. We should link them.

2021-02-03 18:25 UTC, lusassl-msft commented on docs/Checks/ExchangeInformation/GeneralServerInformation.md
> +
Will add them as well.

2021-02-04 16:53 UTC, lusassl-msft commented on docs/Checks/FrequentConfigurationIssues/CTSProcessorAffinityPercentageCheck.md
> +This can cause an impact to the server's search performance. This should only be used a temporary fix if no other options are available vs a long term solution.
Prepared the change. Going to resolve the conversation to better track the open items.

2021-02-04 16:54 UTC, lusassl-msft commented on docs/Checks/FrequentConfigurationIssues/TCPIPSettingsCheck.md
> +
Prepared the change. Going to resolve the conversation to better track the open items.

2021-02-04 16:54 UTC, lusassl-msft commented on docs/Checks/NICSettings/GeneralNICInformation.md
> +We show a warning if the NIC driver is older than 1 year
Prepared the change. Going to resolve the conversation to better track the open items.

2021-02-04 16:55 UTC, lusassl-msft commented on docs/Checks/NICSettings/PackageLossCheck.md
> +Package Loss Check
Prepared the change. Going to resolve the conversation to better track the open items.

2021-02-04 16:55 UTC, lusassl-msft commented on docs/Checks/NICSettings/PackageLossCheck.md
> +======
Prepared the change. Going to resolve the conversation to better track the open items.

2021-02-04 16:56 UTC, lusassl-msft commented on docs/Checks/OSInformation/GeneralOSInformation.md
> +- Power Plan
Prepared the change. Going to resolve the conversation to better track the open items.

2021-02-04 16:57 UTC, lusassl-msft commented on docs/Checks/NICSettings/GeneralNICInformation.md
> +- IPv6 Address
Prepared the change. Going to resolve the conversation to better track the open items.

2021-02-04 17:11 UTC, lusassl-msft commented on docs/Checks/NICSettings/SleepyNICCheck.md
> +======
Prepared the change. Going to resolve the conversation to better track the open items.

2021-02-04 17:20 UTC, lusassl-msft commented on docs/Checks/NICSettings/RSSEnabledCheck.md
> +RSS Enabled Check
Prepared the change. Going to resolve the conversation to better track the open items.

2021-02-04 17:23 UTC, lusassl-msft commented on docs/Checks/NICSettings/GeneralNICInformation.md
> +- Packets Received Discarded
Prepared the change. Going to resolve the conversation to better track the open items.

2021-02-04 17:39 UTC, lusassl-msft commented on docs/Checks/NICSettings/GeneralNICInformation.md
> +- RSS Status
Prepared the change. Going to resolve the conversation to better track the open items.

2021-02-05 10:44 UTC, lusassl-msft commented on docs/Checks/ExchangeInformation/MAPIFrontEndAppPoolGCModeCheck.md
> +
Added the steps to modify the config.

2021-02-05 11:02 UTC, lusassl-msft commented on docs/Checks/NICSettings/GeneralNICInformation.md
> +**Description:**
Added the information.

2021-02-08 15:00 UTC, dpaulson45 approved these changes

2021-02-08 15:05 UTC, merged